const locales = {
  en: {
    navDownload: 'Download',
    navFaq: 'FAQ',
    trustFree: 'Free',
    trustOss: 'Open source',
    trustNoAccount: 'No account',
    trustPrivate: 'Privacy-friendly',
    feat5Label: '05 / ALERTS',
    feat5H3: 'Get alerted when something interesting appears.',
    feat5P: 'Set alerts for aircraft nearby, specific registrations, callsigns, SQUAWK codes or locations — including emergency squawks 7500, 7600, 7700.',
    feat6Label: '06 / FEEDERS',
    feat6H3: 'Running an airplanes.live feeder?',
    feat6P: 'Monitor your feeder status and receive offline notifications if it goes down, straight from the app.',
    dlTierStableLabel: 'Latest Release',
    dlTierStableNote: 'Requires Android 8.0 (API 26) or newer.',
    dlTierNightlyLabel: 'Nightly / Development',
    dlTierNightlyBtn: 'Get nightly build',
    dlTierNightlyNote: 'Built from the latest commit. May be unstable. For testers and developers.',
    downloadMeta: 'Built in GitHub Actions from the public source. FOSS flavor, no proprietary dependencies.',
    trustPrivacyLink: 'Privacy policy',
    faqEyebrow: 'FAQ',
    faqH2: 'Common questions.',
    faq1Q: 'What is SkyFox?',
    faq1A: 'SkyFox is a free, open-source Android app for tracking live aircraft. It uses ADS-B data from airplanes.live to show nearby flights on an interactive map, with search, watchlists and alerts.',
    faq2Q: 'Is it free?',
    faq2A: 'Yes. SkyFox is free to download and use with no in-app purchases or subscriptions.',
    faq3Q: 'Do I need an account?',
    faq3A: 'No. SkyFox works without any account or registration.',
    faq4Q: 'Where does the aircraft data come from?',
    faq4A: 'Aircraft data is provided by airplanes.live, a community-driven ADS-B network with feeders around the world. SkyFox is independent and not affiliated with airplanes.live.',
    faq5Q: 'Is SkyFox affiliated with airplanes.live?',
    faq5A: 'No. SkyFox is an independent open-source project. It uses airplanes.live as a data source but is not affiliated with, endorsed by, or operated by airplanes.live.',
    faq6Q: 'Why does the app need location permission?',
    faq6A: 'Location permission is used to show aircraft near your current position and to center the map on you. It is not required — you can decline it and pan the map manually.',
    faq7Q: 'How do I install the APK?',
    faq7A: 'Download the APK, open it on your Android device and follow the install prompt. You may need to enable installation from unknown sources in your device settings.',
    faq8Q: 'Is SkyFox available on iOS?',
    faq8A: 'No. SkyFox is Android-only.',
    footerIssues: 'Issues',

    heroTitle: 'Live flight tracking, built for plane spotters.',
    heroLede: 'Track nearby aircraft, search by callsign, registration or HEX, build watchlists and get alerts. Free, open source and no account required.',
    heroEyebrow: 'Free &amp; open-source flight tracking for Android',
    heroMicrocopy: "Free and open source.",
    download: 'Download SkyFox for Android',
    downloadShort: "Download APK \u2197",
    seeInAction: "See it in action \u2193",
    galleryTitle: "Less ceremony. More aircraft.",
    galleryIntro: "Real SkyFox screens from the app, not mockups.",
    labels: ["Live map", "Search", "Watchlist", "Plane details"],
    navFeatures: "What it does",
    navScreens: "Screens",
    navSource: "Source",
    navCta: "Get the APK \u2197",
    signalOne: "Map first.",
    signalOneDesc: "What's flying near you, right now.",
    signalTwo: "Search deep.",
    signalTwoDesc: "HEX, callsign, registration, airframe, SQUAWK.",
    signalThree: "Stay private.",
    signalThreeDesc: "No account needed to start spotting.",
    featuresEyebrow: "Built for looking up",
    featuresH2: 'The useful parts of flight tracking.',
    feat1Label: "01 / LIVE MAP",
    feat1H3: 'See what's overhead.',
    feat1P: 'Live aircraft on a clear interactive map. Selectable layers, location controls, filters and a focused detail view per aircraft.',
    feat2Label: "02 / SEARCH",
    feat2H3: 'Find the aircraft you just saw.',
    feat2P: 'Search by HEX, callsign, registration, airframe type or SQUAWK and jump straight to its details.',
    feat3Label: "03 / WATCHLISTS",
    feat3H3: 'Keep tabs on the interesting ones.',
    feat3P: 'Watch specific aircraft, ICAO addresses, callsigns, registrations or SQUAWKs and receive alerts when they appear.',
    feat4Label: "04 / PLANE DETAILS",
    feat4H3: 'Know exactly what you're looking at.',
    feat4P: 'Registration, operator, route, altitude, speed, heading, vertical rate, registry details and emergency squawk status.',
    feat4Link: 'View source →',
    screensEyebrow: "In the cockpit",
    downloadBtn: 'Download APK',
    downloadChangelog: "What's new",
    downloadEyebrow: 'Free &amp; open source',
    downloadH2: 'Download SkyFox for Android.',
    downloadP: "Nightly APK built from source in GitHub Actions.",
    downloadViewGithub: "View GitHub \u2197",
    trustEyebrow: "Open, independent, honest",
    trustH2: 'No surprises.',
    trustP1: 'SkyFox is an independent project based on the airplanes.live Android app by d4rken (GPL). Aircraft data is provided by airplanes.live. SkyFox is not affiliated with or endorsed by airplanes.live.',
    trustP2: 'Maintained by',
    footerTagline: 'Keep your eyes on the sky.',
    footerReleases: "Releases",
    footerPrivacy: "Privacy",
  },
  de: {
    navDownload: 'Download',
    navFaq: 'FAQ',
    trustFree: 'Kostenlos',
    trustOss: 'Open Source',
    trustNoAccount: 'Kein Konto',
    trustPrivate: 'Datenschutzfreundlich',
    feat5Label: '05 / ALARME',
    feat5H3: 'Benachrichtigt werden, wenn etwas Interessantes erscheint.',
    feat5P: 'Alarme für Flugzeuge in der Nähe, bestimmte Kennzeichen, Rufzeichen, SQUAWK-Codes oder Standorte setzen — einschließlich Notfall-SQUAWKs 7500, 7600, 7700.',
    feat6Label: '06 / FEEDER',
    feat6H3: 'Betreibst du einen airplanes.live-Feeder?',
    feat6P: 'Überwache deinen Feeder-Status und erhalte Offline-Benachrichtigungen, wenn er ausfällt, direkt aus der App.',
    dlTierStableLabel: 'Aktuelle Version',
    dlTierStableNote: 'Erfordert Android 8.0 (API 26) oder neuer.',
    dlTierNightlyLabel: 'Nightly / Entwicklung',
    dlTierNightlyBtn: 'Nightly-Build laden',
    dlTierNightlyNote: 'Aus dem neuesten Commit erstellt. Kann instabil sein. Für Tester und Entwickler.',
    downloadMeta: 'In GitHub Actions aus dem öffentlichen Quellcode erstellt. FOSS-Variante, keine proprietären Abhängigkeiten.',
    trustPrivacyLink: 'Datenschutzrichtlinie',
    faqEyebrow: 'FAQ',
    faqH2: 'Häufige Fragen.',
    faq1Q: 'Was ist SkyFox?',
    faq1A: 'SkyFox ist eine kostenlose Open-Source-Android-App zur Verfolgung von Live-Flugzeugen. Sie nutzt ADS-B-Daten von airplanes.live, um nahegelegene Flüge auf einer interaktiven Karte anzuzeigen, mit Suche, Beobachtungslisten und Alarmen.',
    faq2Q: 'Ist es kostenlos?',
    faq2A: 'Ja. SkyFox ist kostenlos herunterzuladen und zu nutzen, ohne In-App-Käufe oder Abonnements.',
    faq3Q: 'Brauche ich ein Konto?',
    faq3A: 'Nein. SkyFox funktioniert ohne Konto oder Registrierung.',
    faq4Q: 'Woher kommen die Flugzeugdaten?',
    faq4A: 'Flugzeugdaten werden von airplanes.live bereitgestellt, einem gemeinschaftlich betriebenen ADS-B-Netzwerk mit Feedern weltweit. SkyFox ist unabhängig und nicht mit airplanes.live verbunden.',
    faq5Q: 'Ist SkyFox mit airplanes.live verbunden?',
    faq5A: 'Nein. SkyFox ist ein unabhängiges Open-Source-Projekt. Es nutzt airplanes.live als Datenquelle, ist aber nicht mit airplanes.live verbunden, von ihm unterstützt oder betrieben.',
    faq6Q: 'Warum benötigt die App die Standortberechtigung?',
    faq6A: 'Die Standortberechtigung wird verwendet, um Flugzeuge in deiner Nähe anzuzeigen und die Karte auf dich zu zentrieren. Sie ist nicht erforderlich — du kannst sie ablehnen und die Karte manuell verschieben.',
    faq7Q: 'Wie installiere ich die APK?',
    faq7A: 'Lade die APK herunter, öffne sie auf deinem Android-Gerät und folge der Installationsaufforderung. Du musst möglicherweise die Installation aus unbekannten Quellen in deinen Geräteeinstellungen aktivieren.',
    faq8Q: 'Ist SkyFox für iOS verfügbar?',
    faq8A: 'Nein. SkyFox ist nur für Android.',
    footerIssues: 'Probleme',

    heroTitle: "Augen auf den Himmel.",
    heroLede: "SkyFox verfolgt Flüge. Kein Konto, kein Lärm.",
    heroEyebrow: "Live-Flugverfolgung f\u00fcr Android",
    heroMicrocopy: "Kostenlos und open source.",
    download: "Neuestes APK laden \u2197",
    downloadShort: "APK laden \u2197",
    seeInAction: "In Aktion ansehen \u2193",
    galleryTitle: "Weniger Umwege. Mehr Flugzeuge.",
    galleryIntro: "Echte SkyFox-Bildschirme aus der App, keine Mockups.",
    labels: ["Live-Karte", "Suche", "Beobachtungsliste", "Flugdetails"],
    navFeatures: "Funktionen",
    navScreens: "Screenshots",
    navSource: "Quellcode",
    navCta: "APK herunterladen \u2197",
    signalOne: "Karte zuerst.",
    signalOneDesc: "Was gerade in deiner Nähe fliegt.",
    signalTwo: "Tief suchen.",
    signalTwoDesc: "HEX, Rufzeichen, Registrierung, Flugzeugtyp, SQUAWK.",
    signalThree: "Privat bleiben.",
    signalThreeDesc: "Kein Konto n\u00f6tig, um loszulegen.",
    featuresEyebrow: "Zum Nachschlagen gebaut",
    featuresH2: "Die Teile der Flugverfolgung, die zählen.",
    feat1Label: "01 / LIVE-KARTE",
    feat1H3: "Sehen Sie, was sich jetzt bewegt.",
    feat1P: "Live-Karte mit Ebenenwechsel, Standort, Aktualisierung und Filtern. Tippe auf ein Flugzeug für Details.",
    feat2Label: "02 / SUCHE",
    feat2H3: "Finden Sie das gesichtete Flugzeug.",
    feat2P: "Suchen Sie nach HEX-Code, Rufzeichen, Registrierung, Flugzeugtyp oder SQUAWK und springen Sie vom Ergebnis zu den Details.",
    feat3Label: "03 / BEOBACHTUNGSLISTEN",
    feat3H3: "Den Überblick behalten.",
    feat3P: "HEX-Codes, Rufzeichen, Registrierungen und SQUAWKs beobachten. Benachrichtigung, sobald sie auftauchen.",
    feat4Label: "04 / FLUGZEUGDETAILS",
    feat4H3: "Wissen, was \u00fcber Ihnen ist.",
    feat4P: "Registrierung, Betreiber, Route, Live-Position, Registrierungsdaten. Notfall-SQUAWKs werden automatisch markiert.",
    feat4Link: "Code ansehen ↗",
    screensEyebrow: "Im Cockpit",
    downloadBtn: 'APK herunterladen',
    downloadChangelog: 'Was ist neu',
    downloadEyebrow: "Holen",
    downloadH2: "SkyFox installieren.",
    downloadP: "Nächtliche APK aus dem Quellcode in GitHub Actions gebaut.",
    downloadViewGithub: "GitHub ansehen \u2197",
    trustEyebrow: "Offen, unabh\u00e4ngig, ehrlich",
    trustH2: "Öffentlich entwickelt. Keine Überraschungen.",
    trustP1: "SkyFox ist ein unabh\u00e4ngiges Projekt, das auf der airplanes.live Android-App basiert. Es verwendet airplanes.live-Daten und ist weder mit airplanes.live verbunden noch von airplanes.live empfohlen.",
    trustP2: "Gepflegt von ",
    footerTagline: "Flugverfolgung ohne L\u00e4rm.",
    footerReleases: "Releases",
    footerPrivacy: "Datenschutz",
  },
  fr: {
    navDownload: 'Télécharger',
    navFaq: 'FAQ',
    trustFree: 'Gratuit',
    trustOss: 'Open source',
    trustNoAccount: 'Sans compte',
    trustPrivate: 'Respecte la vie privée',
    feat5Label: '05 / ALERTES',
    feat5H3: 'Être alerté quand quelque chose d\'intéressant apparaît.',
    feat5P: 'Définir des alertes pour les aéronefs à proximité, des immatriculations, indicatifs, codes squawk ou positions spécifiques — y compris les squawks d\'urgence 7500, 7600, 7700.',
    feat6Label: '06 / FEEDERS',
    feat6H3: 'Vous gérez un feeder airplanes.live ?',
    feat6P: 'Surveillez le statut de votre feeder et recevez des notifications hors ligne s\'il tombe en panne, directement depuis l\'app.',
    dlTierStableLabel: 'Dernière version',
    dlTierStableNote: 'Nécessite Android 8.0 (API 26) ou supérieur.',
    dlTierNightlyLabel: 'Nightly / Développement',
    dlTierNightlyBtn: 'Télécharger le nightly',
    dlTierNightlyNote: 'Construit depuis le dernier commit. Peut être instable. Pour les testeurs et développeurs.',
    downloadMeta: 'Construit dans GitHub Actions depuis le code source public. Variante FOSS, aucune dépendance propriétaire.',
    trustPrivacyLink: 'Politique de confidentialité',
    faqEyebrow: 'FAQ',
    faqH2: 'Questions fréquentes.',
    faq1Q: 'Qu\'est-ce que SkyFox ?',
    faq1A: 'SkyFox est une application Android gratuite et open source pour suivre les aéronefs en temps réel. Elle utilise les données ADS-B d\'airplanes.live pour afficher les vols à proximité sur une carte interactive, avec recherche, listes de surveillance et alertes.',
    faq2Q: 'Est-ce gratuit ?',
    faq2A: 'Oui. SkyFox est gratuit à télécharger et à utiliser, sans achats intégrés ni abonnements.',
    faq3Q: 'Ai-je besoin d\'un compte ?',
    faq3A: 'Non. SkyFox fonctionne sans aucun compte ni inscription.',
    faq4Q: 'D\'où proviennent les données des aéronefs ?',
    faq4A: 'Les données sont fournies par airplanes.live, un réseau ADS-B communautaire avec des feeders dans le monde entier. SkyFox est indépendant et non affilié à airplanes.live.',
    faq5Q: 'SkyFox est-il affilié à airplanes.live ?',
    faq5A: 'Non. SkyFox est un projet open source indépendant. Il utilise airplanes.live comme source de données mais n\'est pas affilié à, approuvé par, ni exploité par airplanes.live.',
    faq6Q: 'Pourquoi l\'application nécessite-t-elle la permission de localisation ?',
    faq6A: 'La permission de localisation est utilisée pour afficher les aéronefs à proximité et centrer la carte sur vous. Elle n\'est pas requise — vous pouvez la refuser et déplacer la carte manuellement.',
    faq7Q: 'Comment installer l\'APK ?',
    faq7A: 'Téléchargez l\'APK, ouvrez-le sur votre appareil Android et suivez l\'invite d\'installation. Vous devrez peut-être activer l\'installation depuis des sources inconnues dans les paramètres de votre appareil.',
    faq8Q: 'SkyFox est-il disponible sur iOS ?',
    faq8A: 'Non. SkyFox est uniquement disponible sur Android.',
    footerIssues: 'Signaler un problème',

    heroTitle: "Les yeux sur le ciel.",
    heroLede: "SkyFox suit les vols. Pas de compte, pas de bruit.",
    heroEyebrow: "Suivi de vols en direct pour Android",
    heroMicrocopy: "Gratuit et open source.",
    download: "T\u00e9l\u00e9charger le dernier APK \u2197",
    downloadShort: "T\u00e9l\u00e9charger l\u2019APK \u2197",
    seeInAction: "Voir l\u2019application \u2193",
    galleryTitle: "Moins de d\u00e9tour. Plus d\u2019avions.",
    galleryIntro: "De vrais \u00e9crans SkyFox, pas des maquettes.",
    labels: ["Carte en direct", "Recherche", "Suivi", "D\u00e9tails du vol"],
    navFeatures: "Fonctionnalit\u00e9s",
    navScreens: "Captures",
    navSource: "Source",
    navCta: "Obtenir l\u2019APK \u2197",
    signalOne: "La carte d\u2019abord.",
    signalOneDesc: "Ce qui vole près de vous, maintenant.",
    signalTwo: "Recherche avanc\u00e9e.",
    signalTwoDesc: "HEX, indicatif, immatriculation, cellule, SQUAWK.",
    signalThree: "Restez priv\u00e9.",
    signalThreeDesc: "Aucun compte n\u00e9cessaire pour commencer \u00e0 rep\u00e9rer.",
    featuresEyebrow: "Con\u00e7u pour la consultation",
    featuresH2: "Ce qui compte vraiment dans le suivi de vols.",
    feat1Label: "01 / CARTE EN DIRECT",
    feat1H3: "Voyez ce qui bouge maintenant.",
    feat1P: "Carte en direct avec changement de couches, localisation, actualisation et filtres. Appuyez sur un avion pour les détails.",
    feat2Label: "02 / RECHERCHE",
    feat2H3: "Retrouvez celui que vous avez vu.",
    feat2P: "Recherchez par code HEX, indicatif, immatriculation, cellule ou SQUAWK et passez d\u2019un r\u00e9sultat \u00e0 ses d\u00e9tails.",
    feat3Label: "03 / LISTES DE SURVEILLANCE",
    feat3H3: "Gardez un oeil sur les choses.",
    feat3P: "Surveillez les codes HEX, indicatifs, immatriculations et SQUAWKs. Recevez une notification quand ils apparaissent.",
    feat4Label: "04 / D\u00c9TAILS DE L\u2019APPAREIL",
    feat4H3: "Sachez ce qui est au-dessus.",
    feat4P: "Immatriculation, opérateur, route, position en direct, données du registre. SQUAWKs d'urgence signalés automatiquement.",
    feat4Link: "Voir le code ↗",
    screensEyebrow: "Dans le cockpit",
    downloadBtn: 'Télécharger APK',
    downloadChangelog: 'Quoi de neuf',
    downloadEyebrow: "Obtenir",
    downloadH2: "Installer SkyFox.",
    downloadP: "APK nocturne compilé depuis les sources dans GitHub Actions.",
    downloadViewGithub: "Voir GitHub \u2197",
    trustEyebrow: "Ouvert, ind\u00e9pendant, honn\u00eate",
    trustH2: "Développé en public. Pas de surprises.",
    trustP1: "SkyFox est un projet ind\u00e9pendant bas\u00e9 sur l\u2019application Android airplanes.live. Il utilise les donn\u00e9es airplanes.live et n\u2019est ni affili\u00e9 ni approuv\u00e9 par airplanes.live.",
    trustP2: "Maintenu par ",
    footerTagline: "Le suivi de vols sans le bruit.",
    footerReleases: "Releases",
    footerPrivacy: "Confidentialit\u00e9",
  },
  es: {
    navDownload: 'Descargar',
    navFaq: 'FAQ',
    trustFree: 'Gratis',
    trustOss: 'Código abierto',
    trustNoAccount: 'Sin cuenta',
    trustPrivate: 'Respetuoso con la privacidad',
    feat5Label: '05 / ALERTAS',
    feat5H3: 'Recibe alertas cuando aparezca algo interesante.',
    feat5P: 'Configura alertas para aeronaves cercanas, matrículas, indicativos, códigos SQUAWK o ubicaciones específicas — incluidos los squawks de emergencia 7500, 7600, 7700.',
    feat6Label: '06 / ALIMENTADORES',
    feat6H3: '¿Tienes un alimentador de airplanes.live?',
    feat6P: 'Monitorea el estado de tu alimentador y recibe notificaciones sin conexión si se cae, directamente desde la app.',
    dlTierStableLabel: 'Última versión',
    dlTierStableNote: 'Requiere Android 8.0 (API 26) o superior.',
    dlTierNightlyLabel: 'Nightly / Desarrollo',
    dlTierNightlyBtn: 'Obtener build nightly',
    dlTierNightlyNote: 'Compilado desde el último commit. Puede ser inestable. Para testers y desarrolladores.',
    downloadMeta: 'Compilado en GitHub Actions desde el código fuente público. Variante FOSS, sin dependencias propietarias.',
    trustPrivacyLink: 'Política de privacidad',
    faqEyebrow: 'Preguntas frecuentes',
    faqH2: 'Preguntas frecuentes.',
    faq1Q: '¿Qué es SkyFox?',
    faq1A: 'SkyFox es una app Android gratuita y de código abierto para rastrear aeronaves en tiempo real. Usa datos ADS-B de airplanes.live para mostrar vuelos cercanos en un mapa interactivo, con búsqueda, listas de seguimiento y alertas.',
    faq2Q: '¿Es gratuito?',
    faq2A: 'Sí. SkyFox es gratuito para descargar y usar, sin compras dentro de la app ni suscripciones.',
    faq3Q: '¿Necesito una cuenta?',
    faq3A: 'No. SkyFox funciona sin ninguna cuenta ni registro.',
    faq4Q: '¿De dónde vienen los datos de las aeronaves?',
    faq4A: 'Los datos provienen de airplanes.live, una red ADS-B comunitaria con alimentadores en todo el mundo. SkyFox es independiente y no está afiliado a airplanes.live.',
    faq5Q: '¿SkyFox está afiliado a airplanes.live?',
    faq5A: 'No. SkyFox es un proyecto de código abierto independiente. Usa airplanes.live como fuente de datos pero no está afiliado, respaldado ni operado por airplanes.live.',
    faq6Q: '¿Por qué la app necesita permiso de ubicación?',
    faq6A: 'El permiso de ubicación se usa para mostrar aeronaves cercanas y centrar el mapa en tu posición. No es obligatorio — puedes rechazarlo y mover el mapa manualmente.',
    faq7Q: '¿Cómo instalo el APK?',
    faq7A: 'Descarga el APK, ábrelo en tu dispositivo Android y sigue el asistente de instalación. Es posible que debas habilitar la instalación desde fuentes desconocidas en los ajustes de tu dispositivo.',
    faq8Q: '¿SkyFox está disponible en iOS?',
    faq8A: 'No. SkyFox es solo para Android.',
    footerIssues: 'Problemas',

    heroTitle: "Ojos en el cielo.",
    heroLede: "SkyFox rastrea vuelos. Sin cuenta, sin ruido.",
    heroEyebrow: "Seguimiento de vuelos en vivo para Android",
    heroMicrocopy: "Gratuito y de código abierto.",
    download: "Descargar el APK m\u00e1s reciente \u2197",
    downloadShort: "Descargar APK \u2197",
    seeInAction: "Verlo en acci\u00f3n \u2193",
    galleryTitle: "Menos ruido. M\u00e1s aviones.",
    galleryIntro: "Pantallas reales de SkyFox, no maquetas.",
    labels: ["Mapa en directo", "B\u00fasqueda", "Seguimiento", "Detalles del avi\u00f3n"],
    navFeatures: "Funciones",
    navScreens: "Pantallas",
    navSource: "C\u00f3digo fuente",
    navCta: "Obtener el APK \u2197",
    signalOne: "El mapa primero.",
    signalOneDesc: "Lo que vuela cerca de ti, ahora mismo.",
    signalTwo: "B\u00fasqueda profunda.",
    signalTwoDesc: "HEX, indicativo, matr\u00edcula, c\u00e9lula, SQUAWK.",
    signalThree: "Mant\u00e9n tu privacidad.",
    signalThreeDesc: "No necesitas cuenta para empezar a observar.",
    featuresEyebrow: "Construido para consultar",
    featuresH2: "Las partes del rastreo de vuelos que importan.",
    feat1Label: "01 / MAPA EN VIVO",
    feat1H3: "Ve lo que se mueve ahora.",
    feat1P: "Mapa en vivo con cambio de capas, ubicación, actualización y filtros. Toca cualquier aeronave para ver detalles.",
    feat2Label: "02 / B\u00daSQUEDA",
    feat2H3: "Encuentra el que viste.",
    feat2P: "Busca por c\u00f3digo HEX, indicativo, matr\u00edcula, c\u00e9lula o SQUAWK y salta de un resultado a sus detalles.",
    feat3Label: "03 / LISTAS DE SEGUIMIENTO",
    feat3H3: "Sigue la pista de las cosas.",
    feat3P: "Vigila códigos HEX, indicativos, matrículas y SQUAWKs. Recibe notificaciones cuando aparezcan.",
    feat4Label: "04 / DETALLES DEL AVI\u00d3N",
    feat4H3: "Sabe qu\u00e9 hay sobre ti.",
    feat4P: "Matrícula, operador, ruta, posición en vivo, datos del registro. SQUAWKs de emergencia marcados automáticamente.",
    feat4Link: "Ver el código ↗",
    screensEyebrow: "En el cockpit",
    downloadBtn: 'Descargar APK',
    downloadChangelog: 'Novedades',
    downloadEyebrow: "Obtener",
    downloadH2: "Instalar SkyFox.",
    downloadP: "APK nocturna compilada desde el código fuente en GitHub Actions.",
    downloadViewGithub: "Ver GitHub \u2197",
    trustEyebrow: "Abierto, independiente, honesto",
    trustH2: "Desarrollado en público. Sin sorpresas.",
    trustP1: "SkyFox es un proyecto independiente basado en la aplicaci\u00f3n Android airplanes.live. Utiliza datos de airplanes.live y no est\u00e1 afiliado ni respaldado por airplanes.live.",
    trustP2: "Mantenido por ",
    footerTagline: "Seguimiento de vuelos sin el ruido.",
    footerReleases: "Releases",
    footerPrivacy: "Privacidad",
  },
  it: {
    navDownload: 'Scarica',
    navFaq: 'FAQ',
    trustFree: 'Gratuito',
    trustOss: 'Open source',
    trustNoAccount: 'Nessun account',
    trustPrivate: 'Privacy-friendly',
    feat5Label: '05 / AVVISI',
    feat5H3: 'Ricevi avvisi quando appare qualcosa di interessante.',
    feat5P: 'Imposta avvisi per aeromobili nelle vicinanze, immatricolazioni, indicativi, codici SQUAWK o posizioni specifiche — inclusi gli squawk di emergenza 7500, 7600, 7700.',
    feat6Label: '06 / FEEDER',
    feat6H3: 'Gestisci un feeder airplanes.live?',
    feat6P: 'Monitora lo stato del tuo feeder e ricevi notifiche offline se va offline, direttamente dall\'app.',
    dlTierStableLabel: 'Ultima versione',
    dlTierStableNote: 'Richiede Android 8.0 (API 26) o versioni successive.',
    dlTierNightlyLabel: 'Nightly / Sviluppo',
    dlTierNightlyBtn: 'Scarica nightly',
    dlTierNightlyNote: 'Compilato dall\'ultimo commit. Può essere instabile. Per tester e sviluppatori.',
    downloadMeta: 'Compilato in GitHub Actions dal codice sorgente pubblico. Variante FOSS, nessuna dipendenza proprietaria.',
    trustPrivacyLink: 'Informativa sulla privacy',
    faqEyebrow: 'FAQ',
    faqH2: 'Domande frequenti.',
    faq1Q: 'Cos\'è SkyFox?',
    faq1A: 'SkyFox è un\'app Android gratuita e open source per tracciare aeromobili in tempo reale. Usa dati ADS-B da airplanes.live per mostrare i voli nelle vicinanze su una mappa interattiva, con ricerca, liste di sorveglianza e avvisi.',
    faq2Q: 'È gratuito?',
    faq2A: 'Sì. SkyFox è gratuito da scaricare e usare, senza acquisti in-app né abbonamenti.',
    faq3Q: 'Ho bisogno di un account?',
    faq3A: 'No. SkyFox funziona senza account o registrazione.',
    faq4Q: 'Da dove provengono i dati degli aeromobili?',
    faq4A: 'I dati provengono da airplanes.live, una rete ADS-B gestita dalla comunità con feeder in tutto il mondo. SkyFox è indipendente e non affiliato ad airplanes.live.',
    faq5Q: 'SkyFox è affiliato ad airplanes.live?',
    faq5A: 'No. SkyFox è un progetto open source indipendente. Usa airplanes.live come fonte di dati ma non è affiliato, approvato né gestito da airplanes.live.',
    faq6Q: 'Perché l\'app ha bisogno del permesso di localizzazione?',
    faq6A: 'Il permesso di localizzazione è usato per mostrare gli aeromobili vicini e centrare la mappa su di te. Non è obbligatorio — puoi rifiutarlo e spostare la mappa manualmente.',
    faq7Q: 'Come installo l\'APK?',
    faq7A: 'Scarica l\'APK, aprilo sul tuo dispositivo Android e segui la procedura di installazione. Potrebbe essere necessario abilitare l\'installazione da fonti sconosciute nelle impostazioni del dispositivo.',
    faq8Q: 'SkyFox è disponibile su iOS?',
    faq8A: 'No. SkyFox è solo per Android.',
    footerIssues: 'Segnalazioni',

    heroTitle: "Occhi sul cielo.",
    heroLede: "SkyFox traccia i voli. Nessun account, nessun rumore.",
    heroEyebrow: "Tracciamento voli in diretta per Android",
    heroMicrocopy: "Gratuito e open source.",
    download: "Scarica l\u2019ultimo APK \u2197",
    downloadShort: "Scarica APK \u2197",
    seeInAction: "Guardalo in azione \u2193",
    galleryTitle: "Meno rumore. Pi\u00f9 aerei.",
    galleryIntro: "Schermate reali di SkyFox, non mockup.",
    labels: ["Mappa live", "Ricerca", "Monitoraggio", "Dettagli del volo"],
    navFeatures: "Funzionalit\u00e0",
    navScreens: "Schermate",
    navSource: "Sorgente",
    navCta: "Scarica l\u2019APK \u2197",
    signalOne: "La mappa prima.",
    signalOneDesc: "Cosa sta volando vicino a te, adesso.",
    signalTwo: "Ricerca approfondita.",
    signalTwoDesc: "HEX, indicativo, immatricolazione, cellula, SQUAWK.",
    signalThree: "Rimani privato.",
    signalThreeDesc: "Nessun account necessario per iniziare a osservare.",
    featuresEyebrow: "Costruito per consultare",
    featuresH2: "Le parti del tracciamento voli che contano.",
    feat1Label: "01 / MAPPA IN DIRETTA",
    feat1H3: "Vedi cosa si muove ora.",
    feat1P: "Mappa live con cambio livelli, posizione, aggiornamento e filtri. Tocca un aereo per i dettagli.",
    feat2Label: "02 / RICERCA",
    feat2H3: "Trova quello che hai visto.",
    feat2P: "Cerca per codice HEX, indicativo, immatricolazione, cellula o SQUAWK e passa da un risultato ai suoi dettagli.",
    feat3Label: "03 / LISTE DI CONTROLLO",
    feat3H3: "Tieni d'occhio le cose.",
    feat3P: "Monitora codici HEX, indicativi, immatricolazioni e SQUAWKs. Ricevi notifiche quando compaiono.",
    feat4Label: "04 / DETTAGLI AEREO",
    feat4H3: "Sapere cosa c\u2019\u00e8 in alto.",
    feat4P: "Immatricolazione, operatore, rotta, posizione live, dati del registro. SQUAWKs di emergenza segnalati automaticamente.",
    feat4Link: "Leggi il codice ↗",
    screensEyebrow: "In cabina di pilotaggio",
    downloadBtn: 'Scarica APK',
    downloadChangelog: 'Novità',
    downloadEyebrow: "Scarica",
    downloadH2: "Installa SkyFox.",
    downloadP: "APK notturna compilata dal sorgente in GitHub Actions.",
    downloadViewGithub: "Visualizza GitHub \u2197",
    trustEyebrow: "Aperto, indipendente, onesto",
    trustH2: "Sviluppato in pubblico. Nessuna sorpresa.",
    trustP1: "SkyFox \u00e8 un progetto indipendente basato sull\u2019app Android airplanes.live. Utilizza i dati di airplanes.live e non \u00e8 affiliato n\u00e9 approvato da airplanes.live.",
    trustP2: "Mantenuto da ",
    footerTagline: "Tracciamento voli senza il rumore.",
    footerReleases: "Releases",
    footerPrivacy: "Privacy",
  },
};

const gallery = document.querySelector("#gallery");
const localeSelect = document.querySelector("#locale");
const galleryButtons = [...document.querySelectorAll("[data-gallery-locale]")];
const screens = ["map", "search", "watch", "plane-details"];

function renderGallery(locale) {
  const copy = locales[locale] || locales.en;
  gallery.innerHTML = screens.map((screen, index) => `
    <figure>
      <img src="assets/screenshots/${locale}/${screen}.png" alt="SkyFox ${copy.labels[index]}" loading="lazy">
      <figcaption><span>0${index + 1}</span> ${copy.labels[index]}</figcaption>
    </figure>
  `).join("");
  galleryButtons.forEach((button) => button.classList.toggle("active", button.dataset.galleryLocale === locale));
}

function applyLocale(locale) {
  const copy = locales[locale] || locales.en;
  document.documentElement.lang = locale;
  document.title = `SkyFox, ${copy.galleryTitle.toLowerCase()}`;
  document.querySelectorAll("[data-i18n]").forEach((element) => {
    const value = copy[element.dataset.i18n];
    if (value) element.textContent = value;
  });
  localeSelect.value = locale;
  renderGallery(locale);
  localStorage.setItem("skyfox-locale", locale);
}

const requestedLocale = new URLSearchParams(location.search).get("lang");
const initialLocale = locales[requestedLocale] ? requestedLocale : (localStorage.getItem("skyfox-locale") || "en");
applyLocale(initialLocale);
localeSelect.addEventListener("change", (event) => applyLocale(event.target.value));
galleryButtons.forEach((button) => button.addEventListener("click", () => {
  applyLocale(button.dataset.galleryLocale);
  localeSelect.value = button.dataset.galleryLocale;
}));

document.querySelectorAll('a[href^="#"]').forEach((link) => {
  link.addEventListener("click", (event) => {
    const target = document.querySelector(link.getAttribute("href"));
    if (!target) return;
    event.preventDefault();
    target.scrollIntoView({ behavior: "smooth", block: "start" });
  });
});

// Latest release badge
async function loadRelease() {
  try {
    const r = await fetch('https://api.github.com/repos/taynotfound/skyfox/releases/latest');
    const d = await r.json();
    if (!d.tag_name) return;
    const tag = document.getElementById('release-tag');
    const dl  = document.getElementById('release-dl');
    const notes = document.getElementById('release-notes');
    const apk = d.assets?.find(a => a.name.endsWith('.apk'));
    if (tag) tag.textContent = d.tag_name;
    if (dl && apk) dl.href = apk.browser_download_url;
    if (notes) notes.href = d.html_url;
  } catch(_) {}
}
document.addEventListener('DOMContentLoaded', loadRelease);
