const locales = {
  en: {
    heroTitle: "Eyes on the sky.",
    heroLede: "SkyFox tracks flights. No account, no noise.",
    heroEyebrow: "Live flight tracking for Android",
    heroMicrocopy: "Free and open source.",
    download: "Download the latest APK \u2197",
    downloadShort: "Download APK \u2197",
    seeInAction: "See it in action \u2193",
    galleryTitle: "Less ceremony. More aircraft.",
    galleryIntro: "Real SkyFox screens from the app, not mockups.",
    labels: ["Live map", "Search", "Watchlist", "Plane details"],
    navFeatures: "What it does",
    navScreens: "Screens",
    navSource: "Source",
    navCta: "Get the APK \u2197",
    signalOne: "Map first.",
    signalOneDesc: "What's flying near you, right now.",
    signalTwo: "Search deep.",
    signalTwoDesc: "HEX, callsign, registration, airframe, SQUAWK.",
    signalThree: "Stay private.",
    signalThreeDesc: "No account needed to start spotting.",
    featuresEyebrow: "Built for looking up",
    featuresH2: "The parts of flight tracking that matter.",
    feat1Label: "01 / LIVE MAP",
    feat1H3: "See what is moving now.",
    feat1P: "Live map with layer switching, location, refresh, and filters. Tap any aircraft for details.",
    feat2Label: "02 / SEARCH",
    feat2H3: "Find the one you saw.",
    feat2P: "Search by HEX code, callsign, registration, airframe, or SQUAWK and jump from a result to its details.",
    feat3Label: "03 / WATCHLISTS",
    feat3H3: "Keep tabs on things.",
    feat3P: "Watch HEX codes, callsigns, registrations, and SQUAWKs. Get notified when they show up.",
    feat4Label: "04 / PLANE DETAILS",
    feat4H3: "Know what is overhead.",
    feat4P: "Registration, operator, route, live position, registry data. Emergency SQUAWKs flagged automatically.",
    feat4Link: "Read the code ↗",
    screensEyebrow: "In the cockpit",
    downloadEyebrow: "Get it",
    downloadH2: "Install SkyFox.",
    downloadP: "Nightly APK built from source in GitHub Actions.",
    downloadViewGithub: "View GitHub \u2197",
    trustEyebrow: "Open, independent, honest",
    trustH2: "Built in public. No surprises.",
    trustP1: "SkyFox is an independent project based on the airplanes.live Android app. It uses airplanes.live data and is not affiliated with or endorsed by airplanes.live.",
    trustP2: "Maintained by Tay März.",
    footerTagline: "Flight tracking without the noise.",
    footerReleases: "Releases",
    footerPrivacy: "Privacy",
  },
  de: {
    heroTitle: "Augen auf den Himmel.",
    heroLede: "SkyFox verfolgt Flüge. Kein Konto, kein Lärm.",
    heroEyebrow: "Live-Flugverfolgung f\u00fcr Android",
    heroMicrocopy: "Kostenlos und open source.",
    download: "Neuestes APK laden \u2197",
    downloadShort: "APK laden \u2197",
    seeInAction: "In Aktion ansehen \u2193",
    galleryTitle: "Weniger Umwege. Mehr Flugzeuge.",
    galleryIntro: "Echte SkyFox-Bildschirme aus der App, keine Mockups.",
    labels: ["Live-Karte", "Suche", "Beobachtungsliste", "Flugdetails"],
    navFeatures: "Funktionen",
    navScreens: "Screenshots",
    navSource: "Quellcode",
    navCta: "APK herunterladen \u2197",
    signalOne: "Karte zuerst.",
    signalOneDesc: "Was gerade in deiner Nähe fliegt.",
    signalTwo: "Tief suchen.",
    signalTwoDesc: "HEX, Rufzeichen, Registrierung, Flugzeugtyp, SQUAWK.",
    signalThree: "Privat bleiben.",
    signalThreeDesc: "Kein Konto n\u00f6tig, um loszulegen.",
    featuresEyebrow: "Zum Nachschlagen gebaut",
    featuresH2: "Die Teile der Flugverfolgung, die zählen.",
    feat1Label: "01 / LIVE-KARTE",
    feat1H3: "Sehen Sie, was sich jetzt bewegt.",
    feat1P: "Live-Karte mit Ebenenwechsel, Standort, Aktualisierung und Filtern. Tippe auf ein Flugzeug für Details.",
    feat2Label: "02 / SUCHE",
    feat2H3: "Finden Sie das gesichtete Flugzeug.",
    feat2P: "Suchen Sie nach HEX-Code, Rufzeichen, Registrierung, Flugzeugtyp oder SQUAWK und springen Sie vom Ergebnis zu den Details.",
    feat3Label: "03 / BEOBACHTUNGSLISTEN",
    feat3H3: "Den Überblick behalten.",
    feat3P: "HEX-Codes, Rufzeichen, Registrierungen und SQUAWKs beobachten. Benachrichtigung, sobald sie auftauchen.",
    feat4Label: "04 / FLUGZEUGDETAILS",
    feat4H3: "Wissen, was \u00fcber Ihnen ist.",
    feat4P: "Registrierung, Betreiber, Route, Live-Position, Registrierungsdaten. Notfall-SQUAWKs werden automatisch markiert.",
    feat4Link: "Code ansehen ↗",
    screensEyebrow: "Im Cockpit",
    downloadEyebrow: "Holen",
    downloadH2: "SkyFox installieren.",
    downloadP: "Nächtliche APK aus dem Quellcode in GitHub Actions gebaut.",
    downloadViewGithub: "GitHub ansehen \u2197",
    trustEyebrow: "Offen, unabh\u00e4ngig, ehrlich",
    trustH2: "Öffentlich entwickelt. Keine Überraschungen.",
    trustP1: "SkyFox ist ein unabh\u00e4ngiges Projekt, das auf der airplanes.live Android-App basiert. Es verwendet airplanes.live-Daten und ist weder mit airplanes.live verbunden noch von airplanes.live empfohlen.",
    trustP2: "Gepflegt von Tay März.",
    footerTagline: "Flugverfolgung ohne L\u00e4rm.",
    footerReleases: "Releases",
    footerPrivacy: "Datenschutz",
  },
  fr: {
    heroTitle: "Les yeux sur le ciel.",
    heroLede: "SkyFox suit les vols. Pas de compte, pas de bruit.",
    heroEyebrow: "Suivi de vols en direct pour Android",
    heroMicrocopy: "Gratuit et open source.",
    download: "T\u00e9l\u00e9charger le dernier APK \u2197",
    downloadShort: "T\u00e9l\u00e9charger l\u2019APK \u2197",
    seeInAction: "Voir l\u2019application \u2193",
    galleryTitle: "Moins de d\u00e9tour. Plus d\u2019avions.",
    galleryIntro: "De vrais \u00e9crans SkyFox, pas des maquettes.",
    labels: ["Carte en direct", "Recherche", "Suivi", "D\u00e9tails du vol"],
    navFeatures: "Fonctionnalit\u00e9s",
    navScreens: "Captures",
    navSource: "Source",
    navCta: "Obtenir l\u2019APK \u2197",
    signalOne: "La carte d\u2019abord.",
    signalOneDesc: "Ce qui vole près de vous, maintenant.",
    signalTwo: "Recherche avanc\u00e9e.",
    signalTwoDesc: "HEX, indicatif, immatriculation, cellule, SQUAWK.",
    signalThree: "Restez priv\u00e9.",
    signalThreeDesc: "Aucun compte n\u00e9cessaire pour commencer \u00e0 rep\u00e9rer.",
    featuresEyebrow: "Con\u00e7u pour la consultation",
    featuresH2: "Ce qui compte vraiment dans le suivi de vols.",
    feat1Label: "01 / CARTE EN DIRECT",
    feat1H3: "Voyez ce qui bouge maintenant.",
    feat1P: "Carte en direct avec changement de couches, localisation, actualisation et filtres. Appuyez sur un avion pour les détails.",
    feat2Label: "02 / RECHERCHE",
    feat2H3: "Retrouvez celui que vous avez vu.",
    feat2P: "Recherchez par code HEX, indicatif, immatriculation, cellule ou SQUAWK et passez d\u2019un r\u00e9sultat \u00e0 ses d\u00e9tails.",
    feat3Label: "03 / LISTES DE SURVEILLANCE",
    feat3H3: "Gardez un oeil sur les choses.",
    feat3P: "Surveillez les codes HEX, indicatifs, immatriculations et SQUAWKs. Recevez une notification quand ils apparaissent.",
    feat4Label: "04 / D\u00c9TAILS DE L\u2019APPAREIL",
    feat4H3: "Sachez ce qui est au-dessus.",
    feat4P: "Immatriculation, opérateur, route, position en direct, données du registre. SQUAWKs d'urgence signalés automatiquement.",
    feat4Link: "Voir le code ↗",
    screensEyebrow: "Dans le cockpit",
    downloadEyebrow: "Obtenir",
    downloadH2: "Installer SkyFox.",
    downloadP: "APK nocturne compilé depuis les sources dans GitHub Actions.",
    downloadViewGithub: "Voir GitHub \u2197",
    trustEyebrow: "Ouvert, ind\u00e9pendant, honn\u00eate",
    trustH2: "Développé en public. Pas de surprises.",
    trustP1: "SkyFox est un projet ind\u00e9pendant bas\u00e9 sur l\u2019application Android airplanes.live. Il utilise les donn\u00e9es airplanes.live et n\u2019est ni affili\u00e9 ni approuv\u00e9 par airplanes.live.",
    trustP2: "Maintenu par Tay März.",
    footerTagline: "Le suivi de vols sans le bruit.",
    footerReleases: "Releases",
    footerPrivacy: "Confidentialit\u00e9",
  },
  es: {
    heroTitle: "Ojos en el cielo.",
    heroLede: "SkyFox rastrea vuelos. Sin cuenta, sin ruido.",
    heroEyebrow: "Seguimiento de vuelos en vivo para Android",
    heroMicrocopy: "Gratuito y de código abierto.",
    download: "Descargar el APK m\u00e1s reciente \u2197",
    downloadShort: "Descargar APK \u2197",
    seeInAction: "Verlo en acci\u00f3n \u2193",
    galleryTitle: "Menos ruido. M\u00e1s aviones.",
    galleryIntro: "Pantallas reales de SkyFox, no maquetas.",
    labels: ["Mapa en directo", "B\u00fasqueda", "Seguimiento", "Detalles del avi\u00f3n"],
    navFeatures: "Funciones",
    navScreens: "Pantallas",
    navSource: "C\u00f3digo fuente",
    navCta: "Obtener el APK \u2197",
    signalOne: "El mapa primero.",
    signalOneDesc: "Lo que vuela cerca de ti, ahora mismo.",
    signalTwo: "B\u00fasqueda profunda.",
    signalTwoDesc: "HEX, indicativo, matr\u00edcula, c\u00e9lula, SQUAWK.",
    signalThree: "Mant\u00e9n tu privacidad.",
    signalThreeDesc: "No necesitas cuenta para empezar a observar.",
    featuresEyebrow: "Construido para consultar",
    featuresH2: "Las partes del rastreo de vuelos que importan.",
    feat1Label: "01 / MAPA EN VIVO",
    feat1H3: "Ve lo que se mueve ahora.",
    feat1P: "Mapa en vivo con cambio de capas, ubicación, actualización y filtros. Toca cualquier aeronave para ver detalles.",
    feat2Label: "02 / B\u00daSQUEDA",
    feat2H3: "Encuentra el que viste.",
    feat2P: "Busca por c\u00f3digo HEX, indicativo, matr\u00edcula, c\u00e9lula o SQUAWK y salta de un resultado a sus detalles.",
    feat3Label: "03 / LISTAS DE SEGUIMIENTO",
    feat3H3: "Sigue la pista de las cosas.",
    feat3P: "Vigila códigos HEX, indicativos, matrículas y SQUAWKs. Recibe notificaciones cuando aparezcan.",
    feat4Label: "04 / DETALLES DEL AVI\u00d3N",
    feat4H3: "Sabe qu\u00e9 hay sobre ti.",
    feat4P: "Matrícula, operador, ruta, posición en vivo, datos del registro. SQUAWKs de emergencia marcados automáticamente.",
    feat4Link: "Ver el código ↗",
    screensEyebrow: "En el cockpit",
    downloadEyebrow: "Obtener",
    downloadH2: "Instalar SkyFox.",
    downloadP: "APK nocturna compilada desde el código fuente en GitHub Actions.",
    downloadViewGithub: "Ver GitHub \u2197",
    trustEyebrow: "Abierto, independiente, honesto",
    trustH2: "Desarrollado en público. Sin sorpresas.",
    trustP1: "SkyFox es un proyecto independiente basado en la aplicaci\u00f3n Android airplanes.live. Utiliza datos de airplanes.live y no est\u00e1 afiliado ni respaldado por airplanes.live.",
    trustP2: "Mantenido por Tay März.",
    footerTagline: "Seguimiento de vuelos sin el ruido.",
    footerReleases: "Releases",
    footerPrivacy: "Privacidad",
  },
  it: {
    heroTitle: "Occhi sul cielo.",
    heroLede: "SkyFox traccia i voli. Nessun account, nessun rumore.",
    heroEyebrow: "Tracciamento voli in diretta per Android",
    heroMicrocopy: "Gratuito e open source.",
    download: "Scarica l\u2019ultimo APK \u2197",
    downloadShort: "Scarica APK \u2197",
    seeInAction: "Guardalo in azione \u2193",
    galleryTitle: "Meno rumore. Pi\u00f9 aerei.",
    galleryIntro: "Schermate reali di SkyFox, non mockup.",
    labels: ["Mappa live", "Ricerca", "Monitoraggio", "Dettagli del volo"],
    navFeatures: "Funzionalit\u00e0",
    navScreens: "Schermate",
    navSource: "Sorgente",
    navCta: "Scarica l\u2019APK \u2197",
    signalOne: "La mappa prima.",
    signalOneDesc: "Cosa sta volando vicino a te, adesso.",
    signalTwo: "Ricerca approfondita.",
    signalTwoDesc: "HEX, indicativo, immatricolazione, cellula, SQUAWK.",
    signalThree: "Rimani privato.",
    signalThreeDesc: "Nessun account necessario per iniziare a osservare.",
    featuresEyebrow: "Costruito per consultare",
    featuresH2: "Le parti del tracciamento voli che contano.",
    feat1Label: "01 / MAPPA IN DIRETTA",
    feat1H3: "Vedi cosa si muove ora.",
    feat1P: "Mappa live con cambio livelli, posizione, aggiornamento e filtri. Tocca un aereo per i dettagli.",
    feat2Label: "02 / RICERCA",
    feat2H3: "Trova quello che hai visto.",
    feat2P: "Cerca per codice HEX, indicativo, immatricolazione, cellula o SQUAWK e passa da un risultato ai suoi dettagli.",
    feat3Label: "03 / LISTE DI CONTROLLO",
    feat3H3: "Tieni d'occhio le cose.",
    feat3P: "Monitora codici HEX, indicativi, immatricolazioni e SQUAWKs. Ricevi notifiche quando compaiono.",
    feat4Label: "04 / DETTAGLI AEREO",
    feat4H3: "Sapere cosa c\u2019\u00e8 in alto.",
    feat4P: "Immatricolazione, operatore, rotta, posizione live, dati del registro. SQUAWKs di emergenza segnalati automaticamente.",
    feat4Link: "Leggi il codice ↗",
    screensEyebrow: "In cabina di pilotaggio",
    downloadEyebrow: "Scarica",
    downloadH2: "Installa SkyFox.",
    downloadP: "APK notturna compilata dal sorgente in GitHub Actions.",
    downloadViewGithub: "Visualizza GitHub \u2197",
    trustEyebrow: "Aperto, indipendente, onesto",
    trustH2: "Sviluppato in pubblico. Nessuna sorpresa.",
    trustP1: "SkyFox \u00e8 un progetto indipendente basato sull\u2019app Android airplanes.live. Utilizza i dati di airplanes.live e non \u00e8 affiliato n\u00e9 approvato da airplanes.live.",
    trustP2: "Mantenuto da Tay März.",
    footerTagline: "Tracciamento voli senza il rumore.",
    footerReleases: "Releases",
    footerPrivacy: "Privacy",
  },
};

const gallery = document.querySelector("#gallery");
const localeSelect = document.querySelector("#locale");
const galleryButtons = [...document.querySelectorAll("[data-gallery-locale]")];
const screens = ["map", "search", "watch", "plane-details"];

function renderGallery(locale) {
  const copy = locales[locale] || locales.en;
  gallery.innerHTML = screens.map((screen, index) => `
    <figure>
      <img src="assets/screenshots/${locale}/${screen}.png" alt="SkyFox ${copy.labels[index]}" loading="lazy">
      <figcaption><span>0${index + 1}</span> ${copy.labels[index]}</figcaption>
    </figure>
  `).join("");
  galleryButtons.forEach((button) => button.classList.toggle("active", button.dataset.galleryLocale === locale));
}

function applyLocale(locale) {
  const copy = locales[locale] || locales.en;
  document.documentElement.lang = locale;
  document.title = `SkyFox, ${copy.galleryTitle.toLowerCase()}`;
  document.querySelectorAll("[data-i18n]").forEach((element) => {
    const value = copy[element.dataset.i18n];
    if (value) element.textContent = value;
  });
  localeSelect.value = locale;
  renderGallery(locale);
  localStorage.setItem("skyfox-locale", locale);
}

const requestedLocale = new URLSearchParams(location.search).get("lang");
const initialLocale = locales[requestedLocale] ? requestedLocale : (localStorage.getItem("skyfox-locale") || "en");
applyLocale(initialLocale);
localeSelect.addEventListener("change", (event) => applyLocale(event.target.value));
galleryButtons.forEach((button) => button.addEventListener("click", () => {
  applyLocale(button.dataset.galleryLocale);
  localeSelect.value = button.dataset.galleryLocale;
}));

document.querySelectorAll('a[href^="#"]').forEach((link) => {
  link.addEventListener("click", (event) => {
    const target = document.querySelector(link.getAttribute("href"));
    if (!target) return;
    event.preventDefault();
    target.scrollIntoView({ behavior: "smooth", block: "start" });
  });
});
